services:
#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - ./.env
#     environment:
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#       - POSTGRES_USER=${DB_USER}
#       - POSTGRES_DB=${DB_NAME}

  web:
    build: .
    restart: always
    # depends_on:
    #   - db
    # env_file:
    #   - ./.env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py seed_data &&
             gunicorn cocktail_exchange.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - web

  price_simulator:
    build: .
    depends_on:
      - web
    # env_file:
    #   - ./.env
    command: python manage.py simulate_market --interval 30

  dozzle:
    image: amir20/dozzle:v8.9.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

volumes:
  postgres_data:
  static_volume:
  media_volume: